export enum USER_EVENT {
  CREATE_ROOM = 'CREATE_ROOM',
  CREATE_ROOM_FEEDBACK = 'CREATE_ROOM_FEEDBACK',
  CREATE_ROOM_ERROR = 'CREATE_ROOM_ERROR',
  JOIN_ROOM = 'JOIN_ROOM',
  JOIN_ROOM_FEEDBACK_LOBBY = 'JOIN_ROOM_FEEDBACK_LOBBY',
  JOIN_ROOM_FEEDBACK_ROOM = 'JOIN_ROOM_FEEDBACK_ROOM',
  JOIN_ROOM_ERROR = 'JOIN_ROOM_ERROR',
  USER_JOIN_ROOM = 'USER_JOIN_ROOM',
}
